console.log("Hello World");
console.error("Error: Hello World");
console.warn("Warning: Hello World");
console.info("Info: Hello World");
console.debug("Debug: Hello World");
console.log('Trace ================================');
console.trace("Trace: Hello World");
console.log('Trace ================================');
console.dir(console);
console.time("Time: Hello World");
console.timeEnd("Time: Hello World");
console.timeLog("Time: Hello World");
console.timeEnd("Time: Hello World");